name: Build Sign and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        build-root-directory: src/
        arguments: assemble
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: src\app\build\outputs\apk\release\app-release-unsigned.apk

  sign:
    name: Sign
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download APK from build
      uses: actions/download-artifact@v1
      with:
        name: apk

    - uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: apk/
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}


name: Build Release App Bundle

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/your_signing_keystore.jks'
          encodedString: ${{ secrets.SIGNING_KEY }}
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make gradlew executable
        run: chmod +x ./src/gradlew
      - name: build prod
        run: ./src/gradlew app:bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: src/app/build/outputs